---
- name: setup steamdeck
  hosts: steamdeck
  become: yes
  tasks:
    - name: start ssh
      ansible.builtin.systemd:
        state: started
        name: sshd
    - name: install packages
      community.general.flatpak:
        name:
          - com.heroicgameslauncher.hgl
          - com.steamgriddb.steam-rom-manager
          - io.gitlab.librewolf-community
          - io.mpv.Mpv
          - org.prismlauncher.PrismLauncher
          - org.srb2.SRB2
    - name: grab emudeck installer
      ansible.builtin.get_url:
        url: https://www.emudeck.com/EmuDeck.desktop
        dest: /home/deck/Desktop/InstallEmuDeck.desktop
    - name: emudeck files
      become: false
      ansible.posix.synchronize:
        src: ~/Emulation
        dest: /run/media/mmcblk0p1/
        mode: push
    - name: grab sonic robo battle 2 sonic 2006
      ansible.builtin.get_url:
        url: https://mb.srb2.org/addons/sonic-2006-extended-port.157/version/5236/download?file=57797
        dest: /home/deck/.var/app/org.srb2.SRB2/.srb2/addons/sonic2006.pk3
    - name: grab sonic robo battle 2 angel island tour
      ansible.builtin.get_url:
        url: https://mb.srb2.org/addons/angel-island-tour.3131/download
        dest: /home/deck/.var/app/org.srb2.SRB2/.srb2/addons/angel_island.pk3
    - name: grab sonic robo battle 2 emerald quest
      ansible.builtin.get_url:
        url: https://mb.srb2.org/addons/emerald-quest.4605/download
        dest: /home/deck/.var/app/org.srb2.SRB2/.srb2/addons/emerald_quest.pk3
